# Generated by Django 4.2.5 on 2023-10-23 02:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosProfesionales',
            fields=[
                ('id_profesional', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=60)),
                ('apellido', models.CharField(default='', max_length=60)),
                ('mail', models.EmailField(default='', max_length=100)),
                ('cuit', models.CharField(default='', max_length=11)),
                ('razon_social', models.CharField(default='', max_length=60)),
                ('especialidad', models.CharField(default='', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=60)),
                ('apellido', models.CharField(default='', max_length=60)),
                ('obra_social', models.CharField(default='', max_length=60)),
                ('numero_os', models.IntegerField(default=0)),
                ('avatar', models.ImageField(default="{% static 'AppTurnero/ava1.jpeg' %}", upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='HorariosProfesionales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(default='', max_length=10)),
                ('hora_inicio', models.TimeField(default=datetime.datetime.now)),
                ('hora_fin', models.TimeField(default=datetime.datetime.now)),
                ('duracion_consulta', models.IntegerField(default=0)),
                ('id_profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppTurnero.datosprofesionales')),
            ],
        ),
        migrations.CreateModel(
            name='AgendaDisponible',
            fields=[
                ('id_agenda', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('disponibilidad', models.CharField(default='Y', max_length=1)),
                ('id_profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppTurnero.datosprofesionales')),
            ],
        ),
        migrations.CreateModel(
            name='AgendaAsignada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppTurnero.agendadisponible')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppTurnero.pacientes')),
            ],
        ),
    ]
