# Generated by Django 4.2.5 on 2023-10-03 03:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTurnero', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosprofesionales',
            name='cuit',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='horariosprofesionales',
            name='hora_fin',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='horariosprofesionales',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='meses',
            name='hora',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
