# Generated by Django 4.2.5 on 2023-10-03 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTurnero', '0002_alter_datosprofesionales_cuit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientes',
            name='avatar',
            field=models.ImageField(default="{% static 'AppTurnero/ava1.jpeg' %}", upload_to=''),
        ),
    ]
