# Generated by Django 4.2.5 on 2023-10-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTurnero', '0004_pacientes_numero_os'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosprofesionales',
            name='mail',
            field=models.EmailField(default='', max_length=60),
        ),
    ]
