# Generated by Django 4.2.5 on 2023-10-05 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTurnero', '0005_alter_datosprofesionales_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosprofesionales',
            name='mail',
            field=models.EmailField(default='', max_length=100),
        ),
    ]
